// <auto-generated />
namespace SimplePhotoGallery.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removeVirtualCollection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeVirtualCollection));
        
        string IMigrationMetadata.Id
        {
            get { return "201307211445100_removeVirtualCollection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
