// <auto-generated />
namespace SimplePhotoGallery.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddArtistAndImageParent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddArtistAndImageParent));
        
        string IMigrationMetadata.Id
        {
            get { return "201306301656446_AddArtistAndImageParent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
